# This is a basic workflow to help you get started with Actions

name: Build and tests NextJs application CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the Main branch
  push:
    branches: [ Main ]
  pull_request:
    branches: [ Main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node_version: [12.x, 14.x, 15.x]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Runs a single command using the runners shell
      - name: npm ci, build and tes
        run: |
          npm ci
          npm runn --if-present
          npm test

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
